### ISSUE TITLE
Update required for 1.13

### ISSUE THREAD

**Issue by SlimeDog** [Phoenix616/NamechangeSimulator#1]
Please update to support Spigot 1.13

**Comment by SlimeDog** [comment]
and 1.13.1

**Comment by SlimeDog** [comment]
Are you thinking of releasing this change?

**Comment by Phoenix616** [comment]
It's already available on the development build server ;)

**Comment by SlimeDog** [comment]
That's the build I tried (build #10). The name doesn't change. The commands are executed without error, and the name is shown in config.yml, but in-game, the original name is shown rather than the fake name.
