### ISSUE TITLE
Name doesn't change

### ISSUE THREAD

**Issue by SlimeDog** [Phoenix616/NamechangeSimulator#3]
Spigot 1.13.2
NamechangeSimulator 1.1.1-b10

> @Phoenix616 Phoenix616 closed this in [0a18370](
https://github.com/Phoenix616/NamechangeSimulator/commit/0a18370d4bd7f301c682275b9ee0a29d8c16aa79) 8 days ago
  
SlimeDog commented 2 days ago
> Are you thinking of releasing this change?

Phoenix616 commented 2 days ago
> It's already available on the development build server ;)
  
That's the build I tried (see version above). The in-game name doesn't change. The commands are executed without error, and the name is shown in _config.yml_, but the original name is shown rather than the fake name.

**Comment by Phoenix616** [comment]
Yeah, the startup error prevented it from working.
